### ISSUE TITLE
Jpeg has false colors

### ISSUE THREAD

**Issue by alexkazik** [Twinside/Juicy.Pixels#139] opened 2017-03-04 14:59 UTC
If an RGB image is written to a JPEG it is not automatically converted to YCbCr and is larger, seems to be too short (GIMP, jpegtopnm and djpeg complain about "premature end of data segment") and the built in viewers in Mac OS and Photoshop Elements show it in false colors.

Please see here for the initial discovery: https://github.com/lehins/hip/issues/11

**Comment by lehins** [comment] 2017-03-04 15:43
This is likely related to #131, which was fixed in 3.2.7.2, but it seems that "shitty fix" turned out to be... well... shitty :)
Details are in lehins/hip#11, but to sum up the issue:
* seems to happen on Mac OS (cannot reproduce it on Ubuntu 16.04)
* affects JPEG images encoded in RGB8 color space.

**Comment by Twinside** [comment] 2017-03-05 20:03
Sadly I don't think this is related to #131, for which I've made a non-shity© fix (aherm).

I'll have some problem to reproduce the issue: I don't have Mac OS nor Photoshop Elements. But given the name of one of the software, I've added the writing of the Adobe infamous APP14 segment which can help specify the color space used in the JPEG file. If you could test HEAD and report the result that would be great.

**Comment by alexkazik** [comment] 2017-03-05 20:49
That does solve the problem (correct colors in Mac OS viewers and Photoshop Express and also djpeg is no longer complaining).

I'm curious why are they not converted to YCbCr automatically? That's smaller (and works).

**Comment by Twinside** [comment] 2017-03-05 21:31
Well using [`encodeDirectJpegAtQualityWithMetadata`](http://hackage.haskell.org/package/JuicyPixels-3.2.8/docs/Codec-Picture-Jpg.html#v:encodeDirectJpegAtQualityWithMetadata) you can encode any known color-space you want, it's a function that has been asked. The proper way to encode a jpeg is through [`encodeJpegAtQualityWithMetadata`](http://hackage.haskell.org/package/JuicyPixels-3.2.8/docs/Codec-Picture-Jpg.html#v:encodeJpegAtQualityWithMetadata) (without the direct).

And for why there isn't any automatic conversion for Jpeg encoding, there is one actually: [`Codec.Picture.Saving.imageToJpg`](http://hackage.haskell.org/package/JuicyPixels-3.2.8/docs/Codec-Picture-Saving.html#v:imageToJpg). It's not the default because any color conversion is potentially lossy and I prefer to make them explicit as much as possible.

I'll upload the fixed package on Hackage tomorrow :)

**Closed by Twinside** 2017-03-05 21:31 UTC
Labels: bug
