### ISSUE TITLE
QuickCheck'ing images

### ISSUE THREAD

**Issue by ayberkt** [Twinside/Juicy.Pixels#111] opened 2015-11-05 18:11 UTC
I'm new to QuickCheck so I hope this is a sensible question. I want to be able to run QuickCheck on images. How should I go about making the ```Image``` type an instance of arbitrary? I believe I need to make each pixel type (e.g. ```PixelRGBA8```) an instance of arbitrary first, then proceed to making ```Image a``` one. I also presume that ```Image a``` should be an instance of ```Eq``` too, to be able to run any kind of useful test.

Are there any problems with this approach?

**Comment by gaa-cifasis** [comment] 2015-11-05 19:35
@ayberk 
We have some basic arbitrary instances of the Juicy.Pixels images in [QuickFuzz](http://quickfuzz.org/) in case you want to look at some code.

**Comment by ayberk** [comment] 2015-11-05 20:46
@ayberkt 😗

**Comment by ayberkt** [comment] 2015-11-05 20:49
@gaa-cifasis Thanks!

**Comment by Twinside** [comment] 2015-11-06 08:37
not a bug/feature request, closing ticket

**Closed by Twinside** 2015-11-06 08:37 UTC
